/* 部门 */
var Department = [{
    DepID: 1,
    DepName: '园长办公室',
    // PersonCount: 2,
    Remark: ''
}, {
    DepID: 2,
    DepName: '教学部',
    // PersonCount: 2,
    Remark: ''
}];

let BulletinList = [{
    Id: 1,
    Title: "根据省疫情防控工作要求我市第七批次学校开学时间公布",
    Content: "根据省疫情防控工作领导小组学校防控组要求，经市疫情防控应急指挥部批准，全市幼儿园大班以外的其他年级和特殊教育学校于5月25日开学。",
    Author: "李娜",
    Time: "2020.5.15"
}, {
    Id: 2,
    Title: "根据省疫情防控工作要求我市第六批次学校开学时间公布",
    Content: "根据省疫情防控工作领导小组学校防控组要求，经市疫情防控应急指挥部批准，全市幼儿园大班于5月18日开学。\n" +
        "        全市幼儿园其他年级和聋哑类以外的特殊教育学校继续做好开学准备，具体开学时间另行公布。",

    Author: "周克涛",
    Time: "2020.5.21"
}, {
    Id: 3,
    Title: "温馨提醒-5-7月份是手足口病高发期，请做好预防工作",
    Content: "5-7月份是手足口病高发期，在家庭中要做好预防工作。不要去人群集中的地方，儿童卫生应注意勤洗手、洗澡，勤换洗衣物，勤晾晒被褥，婴儿奶嘴、奶瓶煮沸消毒 20 分钟后使用，儿童玩具定期清洗； 每天开窗通风至少 2～3 次，每次不少于 30 分钟。",
    Author: "李娜",
    Time: "2020.5.28"
}, {
    Id: 4,
    Title: "文明倡议-疫情防控齐参与，文明行为是基础",
    Content: "1、讲究个人卫生\n" +
        "        2、分类投放垃圾\n" +
        "        3、保护野生动物\n" +
        "        4、自觉移风易俗\n" +
        "        5、减轻人情负担\n" +
        "        6、倡导文明行为\n" +
        "        7、维护社会秩序\n" +
        "        8、普及公共餐具\n" +
        "        9、推广集体分餐\n" +
        "        10、参与志愿服务\n" +
        "        疫情防控齐参与，文明行为是基础。相信按照中央、省的统筹部署，在市委市政府的坚强领导下，在全市人民的共同努力下，我们一定打赢疫情防控的人民战争、总体战、阻击战！\n" +
        "        相信在春暖花开之际，我们一定能够展现出更加文明的新风采和更加蓬勃的新气象！",
    Author: "宋玉红",
    Time: "2020.3.10"
}, {
    Id: 5,
    Title: "【麓山国际双语幼儿园】关于实行校园全封闭式管理的通告",
    Content: "为贯彻落实上级部门关于新型冠状病毒感染的肺炎疫情防控工作需要，切实加强我园新型冠状病毒感染的肺炎疫情的防控工作，保障学园师生的生命安全与身体健康，维护学园正常的教学秩序和校园稳定，经研究决定，永春县一都中心幼儿园即日起实行封闭式管理，现将有关要求通知如下：\n" +
        "        1.自2020年1月29日起，校园实行全封闭管理，谢绝一切外来人员(包括教师家属的亲戚、朋友)来访，禁止一切校内活动。\n" +
        "        2.非本校教职员工因特殊情况确有需要进入校园的需经带班领导同意，并向值班保安出示本人身份证，按要求登记相关信息（姓名、身份证号码、联系电话、从哪里来、现住地址等），请自觉接受体温测量;如符合隔离条件的，请自觉配合隔离。\n" +
        "        3.所有进入校园的人员，必需戴好口罩，配合保卫、值班人员做好体温测量，证件登记工作。\n" +
        "        4.特殊时期，采取非常措施，敬请理解和支持。",
    Author: "周克涛",
    Time: "2020.1.29"
}, {
    Id: 6,
    Title: "2020年寒假放假时间通知",
    Content: "2020年寒假放假时间为1月18日，春季正式开学时间为2月10日。",
    Author: "董燕",
    Time: "2020.1.13"
}, {
    Id: 7,
    Title: "关于网站运维安全隐患的网站公告",
    Content: "根据《中华人民共和国网络安全法》相关内容的要求，学校拟对附属花朵幼儿园、教育幼儿园、姑香苑幼儿园的门户网站进行集群化统一管理与维护。上述3所幼儿园的网站目前是托管于无忧幼儿园网（辽ICP备12004948号）进行管理与维护。由于该公司目前已经无法正常联系到相关管理或维护人员，网站运维存在安全隐患。因此，我校决定于2019年11月23日17:00时停止对三个幼儿园网站的使用。从即日起，网站上出现的任何内容及更新与我校及三所幼儿园无关。",
    Author: "董燕",
    Time: "2019.10.20"
}];


var buMenGuanLI = [{
    xiangMunumber: "1",
    buMenNanme: "保教部",
    fuZeRenname: "张三",
    lianXIDianHua: "13456532654",
    buMenMiaoShu: "负责幼儿园的保育工作",
    buMenRenShu: "3",
    beiZhu: "",
    name1: "请问",
    name2: "我先",
    name3: "伟大",
    phone1: "12235452",
    phone2: "12235452",
    phone3: "12235452",
}, {
    xiangMunumber: "2",
    buMenNanme: "财务部",
    fuZeRenname: "李四",
    lianXIDianHua: "13456532654",
    buMenMiaoShu: "负责学校员工的工资的发放现金收付工作",
    buMenRenShu: "3",
    beiZhu: "",
    name1: "请问",
    name2: "我先",
    name3: "伟大",
    phone1: "12235452",
    phone2: "12235452",
    phone3: "12235452"
}, {
    xiangMunumber: "3",
    buMenNanme: "行政部",
    fuZeRenname: "王五",
    lianXIDianHua: "13456532654",
    buMenMiaoShu: "负责各职能部门的关系协调",
    buMenRenShu: "3",
    beiZhu: "",
    name1: "请问",
    name2: "我先",
    name3: "伟大",
    phone1: "12235452",
    phone2: "12235452",
    phone3: "12235452"
}, {
    xiangMunumber: "4",
    buMenNanme: "人事部",
    fuZeRenname: "李老师",
    lianXIDianHua: "13456532654",
    buMenMiaoShu: "负责个类培训业务的联系及组织",
    buMenRenShu: "0",
    beiZhu: "",
    name1: "请问",
    name2: "我先",
    name3: "伟大",
    phone1: "12235452",
    phone2: "12235452",
    phone3: "12235452"
}, {
    xiangMunumber: "5",
    buMenNanme: "后勤部",
    fuZeRenname: "张老师",
    lianXIDianHua: "13456532654",
    buMenMiaoShu: "负责管理幼儿园教师和孩子的安全以及生活上需求",
    buMenRenShu: "3",
    beiZhu: "",
    name1: "请问",
    name2: "我先",
    name3: "伟大",
    phone1: "12235452",
    phone2: "12235452",
    phone3: "12235452"
}]



var  mmList  =   [{
        Url:   '../../images/photoWall/1.jpg',
    },
    {
        Url:   '../../images/photoWall/2.jpg',
    },
    {
        Url: '../../images/photoWall/3.jpg',
    },
    {
        Url: '../../images/photoWall/4.jpg',
    },
    {
        Url: '../../images/photoWall/5.jpg',
    },
    {
        Url: '../../images/photoWall/6.jpg',
    },
]
var hjList = [{
        Url:   '../../images/photoWall/13.jpg',
    },
    {
        Url:   '../../images/photoWall/14.jpg',
    },
    {
        Url: '../../images/photoWall/15.jpg',
    },
    {
        Url: '../../images/photoWall/16.jpg',
    },
    {
        Url: '../../images/photoWall/17.jpg',
    },
    {
        Url: '../../images/photoWall/18.jpg',
    },
]
var  kkList  =   [{
        Url:   '../../images/photoWall/25.jpg',
    },
    {
        Url:   '../../images/photoWall/26.jpg',
    },
    {
        Url: '../../images/photoWall/27.jpg',
    },
    {
        Url: '../../images/photoWall/28.jpg',
    },
    {
        Url: '../../images/photoWall/29.jpg',
    },
    {
        Url: '../../images/photoWall/30.jpg',
    },
]
var mmSmallList = [{
        Url:   '../../images/photoWall/7.jpg',
    },
    {
        Url:   '../../images/photoWall/8.jpg',
    },
    {
        Url:   '../../images/photoWall/9.jpg',
    },
    {
        Url:   '../../images/photoWall/10.jpg',
    },
    {
        Url:   '../../images/photoWall/11.jpg',
    },
    {
        Url:   '../../images/photoWall/12.jpg',
    },

]

var hjSmallList = [{
        Url:   '../../images/photoWall/19.jpg',
    },
    {
        Url:   '../../images/photoWall/20.jpg',
    },
    {
        Url:   '../../images/photoWall/21.jpg',
    },
    {
        Url:   '../../images/photoWall/22.jpg',
    },
    {
        Url:   '../../images/photoWall/23.jpg',
    },
    {
        Url:   '../../images/photoWall/24.jpg',
    },
]

var kkSmallList = [{
        Url:   '../../images/photoWall/31.jpg',
    },
    {
        Url:   '../../images/photoWall/32.jpg',
    },
    {
        Url:   '../../images/photoWall/33.jpg',
    },
    {
        Url:   '../../images/photoWall/34.jpg',
    },
    {
        Url:   '../../images/photoWall/35.jpg',
    },
    {
        Url:   '../../images/photoWall/36.jpg',
    },
]

var mmTxtList = [{
        title: "5.25篮球运动会",
        content: "第5届篮球运动会，萌萌班小朋友都来比赛啦！加油，你们是最棒的",
    },
    {
        title: "表演",
        content: "萌萌班小朋友换好演出服，准备上台",
    },
    {
        title: "午休时间",
        content: "充足的睡眠是小朋友健康成长的基础，睡觉香香，身体壮壮",
    },
    {
        title: "体验劳作",
        content: "谁知盘中餐，粒粒皆辛苦。小朋友们和爸爸妈妈一起体验田间劳作，分享收获喜悦",
    },
    {
        title: "小小交通员",
        content: "遵守交通安全规则，从我们做起。4月30日，萌萌班小朋友在宝马体验厅模拟交通指挥。看，我的手势标准吗？",
    },
    {
        title: "春暖花开",
        content: "春天来了，萌萌班小朋友跟老师一起郊游、贴近大自然",
    },

]
var hjTxtList = [{
        title: "体育课",
        content: "火箭班集合上体育课啦！开心剪刀手",
    },
    {
        title: "自然课",
        content: "培养观察力，从一片叶子的脉络、颜色、形状开始",
    },
    {
        title: "书画节",
        content: "打开长长的画卷，跟爸爸妈妈一起挥洒想象力、构建五彩世界",
    },
    {
        title: "上学路上",
        content: "童年的快乐在6月的风里，在清晨的阳光下，在每天上学的石板路上",
    },
    {
        title: "运动会",
        content: "年纪小小，能量满满。妈妈陪我来运动",
    },
    {
        title: "课外拓展",
        content: "火箭班课外拓展课，你追我赶、配合无间。",
    },
]

var kkTxtList = [{
        title: "看鱼",
        content: "小鱼也喜欢吃玉米吗？",
    },
    {
        title: "朗诵",
        content: "你是爱，是暖，你是人间四月天    ——卡卡班张曼小朋友在进行诗朗诵",
    },
    {
        title: "慈善竞拍",
        content: "小朋友跟爸爸妈妈一起参加慈善竞拍",
    },
    {
        title: "两人三脚",
        content: "考验配合度的时候到啦！两人三脚，谁能最先到达终点呢？",
    },
    {
        title: "体检",
        content: "跟医生阿姨一起学 “啊——”，卡卡班小朋友在进行体检",
    },
    {
        title: "Hello，Mr.smith",
        content: "小朋友们跟斯密斯老师一起学英文，练习口语",
    },

]

/* 班级级别 */
var ClasGradeList = [{
            'ClasGradeID': '1',
            'Name': '小班'
        },
        {
            'ID': '2',
            'Name': '中班'
        },
        {
            'ID': '3',
            'Name': '大班'
        }
    ]
    /* 班级 */
var ClassList = [{
        'ID': 1,
        'ClassTypeID': '萌萌班',
        'ClasGradeID': '大班',
        'MianTeacher': "王印",
        'DepTeacher': "苏嘉"
    },

    {
        'ID': 2,
        'ClassTypeID': '火箭班',
        'ClasGradeID': '中班',
        'MianTeacher': "小龙",
        'DepTeacher': "刘杰"
    },
    {
        'ID': 3,
        'ClassTypeID': '卡卡班',
        'ClasGradeID': '小班',
        'MianTeacher': "康康",
        'DepTeacher': "小丁丁"
    },
    {
        'ID': 4,
        'ClassTypeID': '花花班',
        'ClasGradeID': '大班',
        'MianTeacher': "康康",
        'DepTeacher': "小丁丁"
    },
    {
        'ID': 5,
        'ClassTypeID': '萌萌班',
        'ClasGradeID': '小班',
        'MianTeacher': "王印",
        'DepTeacher': "苏嘉"
    },
];

/* 班级类型 */
var ClassTypeList = [{
        'ClassTypeID': '1',
        'Name': '萌萌班',
        'ClassGradeName': "小班"
    },
    {
        'ID': '2',
        'Name': '火箭班',
        'ClassGradeName': "小班"
    },
    {
        'ID': '3',
        'Name': '卡卡班',
        'ClassGradeName': "中班"
    },
    {
        'ID': '4',
        'Name': '花花班',
        'ClassGradeName': "大班"
    },
    {
        'ID': '5',
        'Name': '萌萌班',
        'ClassGradeName': "大班"
    }
];


/* 大班学生 */
var BigStudentList = [{
    Role: "BigStudent",
    Grade: "大班",
    Name: " 李兴",
    LinkName1: "李力",
    Relation1: "父子",
    Tel1: 13658018176,
    LinkName2: "",
    Relation2: "",
    Tel2: "",
    Age: 8,
    Sex: "男",
    Arrive: "08:40",
    LeaveSchool: "17:50",
    Attendance: "正常",
    StateName: "正常",
    OperatorName: "admin",
    Email: "1434424324@qq.com",
    Id: 1,
    OperatorName: "admin",
    CreateTime: '2020-01-01',
    Birthday: '2017-01-01',
    StuNO: 0,
    Address: '高新区云华路',
    ClassTypeName: "萌萌班",


}, {
    Role: "BigStudent",
    Grade: "大班",
    Name: "王雪",
    Age: 8,
    Sex: "女",
    LinkName1: "王瑞",
    Tel1: 13658018176,
    LinkName2: "",
    Relation2: "",
    Tel2: "",
    Relation1: "母女",
    Arrive: "08:40",
    LeaveSchool: "17:40",
    Attendance: "正常",
    StateName: "正常",
    Email: "1434424325@qq.com",
    Id: 2,
    OperatorName: "admin",
    CreateTime: '2020-01-01',
    Birthday: '2017-01-01',
    StuNO: 0,
    Address: '',
    ClassTypeName: "萌萌班",
}, {
    Role: "BigStudent",
    Grade: "大班",
    Name: "张红灵",
    Age: 8,
    Sex: "女",
    LinkName1: "袁丹",
    Tel1: 13658018176,
    LinkName2: "",
    Relation2: "",
    Tel2: "",
    Relation: "母女",
    Arrive: "08:10",
    LeaveSchool: "17:50",
    Attendance: "正常",
    StateName: "正常",
    OperatorName: "admin",
    CreateTime: '2020-01-01',
    Birthday: '2017-01-01',
    StuNO: 0,
    Address: '',
    ClassTypeName: "萌萌班",
    Email: "1434424325@qq.com",
    Id: 3
}, {
    Role: "BigStudent",
    Grade: "大班",
    Name: "孟竹",
    LinkName1: "韩雪",
    Age: 8,
    Sex: "男",
    Tel1: 13658018176,
    LinkName2: "",
    Relation2: "",
    Tel2: "",
    Relation1: "母子",
    Arrive: "08:40",
    LeaveSchool: "16:50",
    Attendance: "正常",
    StateName: "正常",
    OperatorName: "admin",
    CreateTime: '2020-01-01',
    Birthday: '2017-01-01',
    StuNO: 0,
    Address: '',
    ClassTypeName: "萌萌班",
    Email: "1434424325@qq.com",
    Id: 4
}, {
    Role: "BigStudent",
    Grade: "大班",
    Name: "王伟鹏",
    LinkName1: "余姗姗",
    Age: 8,
    Sex: "男",
    Tel1: 13658018176,
    LinkName2: "",
    Relation2: "",
    Tel2: "",
    Relation1: "母子",
    Arrive: "08:40",
    LeaveSchool: "17:50",
    Attendance: "正常",
    StateName: "正常",
    OperatorName: "admin",
    CreateTime: '2020-01-01',
    Birthday: '2017-01-01',
    StuNO: 0,
    Address: '',
    ClassTypeName: "萌萌班",
    Email: "1434424325@qq.com",
    Id: 5
}, {
    Role: "BigStudent",
    Grade: "大班",
    Name: "林芳",
    LinkName1: "李艳",
    Age: 8,
    Sex: "女",
    Tel1: 13658018176,
    LinkName2: "",
    Relation2: "",
    Tel2: "",
    Relation1: "母女",
    Arrive: "08:40",
    LeaveSchool: "16:50",
    Attendance: "正常",
    StateName: "正常",
    OperatorName: "admin",
    CreateTime: '2020-01-01',
    Birthday: '2017-01-01',
    StuNO: 0,
    Address: '',
    ClassTypeName: "萌萌班",
    Email: "1434424325@qq.com",
    Id: 6
}, {
    Role: "BigStudent",
    Grade: "大班",
    Name: "黄萍萍",
    LinkName1: "余英姿",
    Age: 8,
    Sex: "女",
    Tel1: 13658018176,
    LinkName2: "",
    Relation2: "",
    Tel2: "",
    Relation1: "母女",
    Arrive: "08:40",
    LeaveSchool: "17:50",
    Attendance: "正常",
    StateName: "正常",
    OperatorName: "admin",
    CreateTime: '2020-01-01',
    Birthday: '2017-01-01',
    StuNO: 0,
    Address: '',
    ClassTypeName: "卡卡班",
    Email: "1434424325@qq.com",
    Id: 7
}, {
    Role: "BigStudent",
    Grade: "大班",
    Name: "唐奇",
    LinkName1: "步雅芸",
    Age: 8,
    Sex: "男",
    Tel1: 13658018176,
    LinkName2: "",
    Relation2: "",
    Tel2: "",
    Relation1: "母子",
    Arrive: "08:40",
    LeaveSchool: "17:50",
    Attendance: "正常",
    StateName: "正常",
    OperatorName: "admin",
    CreateTime: '2020-01-01',
    Birthday: '2017-01-01',
    StuNO: 0,
    Address: '',
    ClassTypeName: "火箭班",
    Email: "1434424325@qq.com",
    Id: 8
}, {
    Role: "BigStudent",
    Grade: "大班",
    Name: "郭子杰",
    LinkName1: "王瑞琪",
    Age: 8,
    Sex: "男",
    Tel1: 13658018176,
    Relation1: "母子",
    LinkName2: "",
    Relation2: "",
    Tel2: "",
    Arrive: "09:40",
    LeaveSchool: "17:50",
    Attendance: "迟到",
    StateName: "正常",
    OperatorName: "admin",
    CreateTime: '2020-01-01',
    Birthday: '2017-01-01',
    StuNO: 0,
    Address: '',
    ClassTypeName: "火箭班",
    Email: "1434424325@qq.com",
    Id: 9
}, {
    Role: "BigStudent",
    Grade: "大班",
    Name: "曹兵",
    LinkName1: "皮庆燕",
    Age: 8,
    Sex: "男",
    Tel1: 13658018176,
    Relation1: "母子",
    LinkName2: "",
    Relation2: "",
    Tel2: "",
    Arrive: "08:40",
    LeaveSchool: "17:50",
    Attendance: "正常",
    StateName: "正常",
    OperatorName: "admin",
    CreateTime: '2020-01-01',
    Birthday: '2017-01-01',
    StuNO: 0,
    Address: '',
    ClassTypeName: "花花班",
    Email: "1434424325@qq.com",
    Id: 10
}];
/* 中班学生 */
var MidStudentList = [{
    Role: "MidStudent",
    Grade: "中班",
    Name: "刘婷婷",
    LinkName1: "王婷",
    Age: 7,
    Sex: "女",
    Tel1: 13658018176,
    Relation1: "母子",
    LinkName2: "",
    Relation2: "",
    Tel2: "",
    Arrive: "08:40",
    LeaveSchool: "17:50",
    Attendance: "正常",
    StateName: "正常",
    OperatorName: "admin",
    CreateTime: '2020-01-01',
    Birthday: '2017-01-01',
    StuNO: 0,
    Address: '',
    ClassTypeName: "卡卡班",
    Email: "1434424325@qq.com",
    Id: 11
}, {
    Role: "MidStudent",
    Grade: "中班",
    Name: "杨燕",
    LinkName1: "何佩芬",
    Age: 7,
    Sex: "女",
    Tel1: 13658018176,
    Relation1: "母子",
    LinkName2: "",
    Relation2: "",
    Tel2: "",
    Arrive: "09:40",
    LeaveSchool: "17:50",
    Attendance: "迟到",
    StateName: "正常",
    OperatorName: "admin",
    CreateTime: '2020-01-01',
    Birthday: '2017-01-01',
    StuNO: 0,
    Address: '',
    ClassTypeName: "卡卡班",
    Email: "1434424325@qq.com",
    Id: 12
}, {
    Role: "MidStudent",
    Grade: "中班",
    Name: "陈思远",
    LinkName1: "周萍",
    Age: 7,
    Sex: "男",
    Tel1: 13658018176,
    Relation1: "母子",
    LinkName2: "",
    Relation2: "",
    Tel2: "",
    Arrive: "08:40",
    LeaveSchool: "16:50",
    Attendance: "正常",
    StateName: "正常",
    OperatorName: "admin",
    CreateTime: '2020-01-01',
    Birthday: '2017-01-01',
    StuNO: 0,
    Address: '',
    ClassTypeName: "卡卡班",
    Email: "1834424325@qq.com",
    Id: 13
}, {
    Role: "MidStudent",
    Grade: "中班",
    Name: "凌玉",
    LinkName1: "陈丹丽",
    Age: 7,
    Sex: "男",
    Tel1: 13658018176,
    Relation1: "母子",
    LinkName2: "",
    Relation2: "",
    Tel2: "",
    Arrive: "09:40",
    LeaveSchool: "17:50",
    Attendance: "迟到",
    StateName: "正常",
    OperatorName: "admin",
    CreateTime: '2020-01-01',
    Birthday: '2017-01-01',
    StuNO: 0,
    Address: '',
    ClassTypeName: "卡卡班",
    Email: "1534424325@qq.com",
    Id: 14
}, {
    Role: "MidStudent",
    Grade: "中班",
    Name: "何杰",
    LinkName1: "朱云瑞",
    Age: 7,
    Sex: "男",
    Tel1: 13658018176,
    Relation1: "母子",
    LinkName2: "",
    Relation2: "",
    Tel2: "",
    Arrive: "08:40",
    LeaveSchool: "17:50",
    Attendance: "正常",
    StateName: "正常",
    OperatorName: "admin",
    CreateTime: '2020-01-01',
    Birthday: '2017-01-01',
    StuNO: 0,
    Address: '',
    ClassTypeName: "卡卡班",
    Email: "1434443325@qq.com",
    Id: 15
}];
/* 小班学生 */
var SmallStudentList = [{
    Role: "SmallStudent",
    Grade: "小班",
    Name: "陈小红",
    LinkName1: "周娟",
    Age: 6,
    Sex: "女",
    Tel1: 13658018176,
    Relation1: "母子",
    LinkName2: "",
    Relation2: "",
    Tel2: "",
    Arrive: "08:40",
    LeaveSchool: "17:50",
    Attendance: "正常",
    StateName: "正常",
    OperatorName: "admin",
    CreateTime: '2020-01-01',
    Birthday: '2017-01-01',
    StuNO: 0,
    Address: '',
    ClassTypeName: "萌萌班",
    Email: "1434422325@qq.com",
    Id: 16
}, {
    Role: "SmallStudent",
    Grade: "小班",
    Name: "张荷",
    LinkName1: "郭淑娟",
    Age: 6,
    Sex: "女",
    Tel1: 13658018176,
    Relation1: "母子",
    LinkName2: "",
    Relation2: "",
    Tel2: "",
    Arrive: "09:20",
    LeaveSchool: "17:50",
    Attendance: "迟到",
    StateName: "正常",
    OperatorName: "admin",
    CreateTime: '2020-01-01',
    Birthday: '2017-01-01',
    StuNO: 0,
    Address: '',
    ClassTypeName: "萌萌班",
    Email: "14344123325@qq.com",
    Id: 17
}, {
    Role: "SmallStudent",
    Grade: "小班",
    Name: "邓杰",
    LinkName1: "李雪飞",
    Age: 6,
    Sex: "男",
    Tel1: 13658018176,
    Relation1: "母子",
    LinkName2: "",
    Relation2: "",
    Tel2: "",
    Arrive: "08:40",
    LeaveSchool: "16:50",
    Attendance: "正常",
    StateName: "正常",
    OperatorName: "admin",
    CreateTime: '2020-01-01',
    Birthday: '2017-01-01',
    StuNO: 0,
    Address: '',
    ClassTypeName: "萌萌班",
    Email: "143324324325@qq.com",
    Id: 18
}, {
    Role: "SmallStudent",
    Grade: "小班",
    Name: "张思琪",
    LinkName1: "晓蕾",
    Age: 6,
    Sex: "女",
    Tel1: 13658018176,
    Relation1: "母子",
    LinkName2: "",
    Relation2: "",
    Tel2: "",
    Arrive: "10:40",
    LeaveSchool: "17:50",
    Attendance: "迟到",
    StateName: "正常",
    OperatorName: "admin",
    CreateTime: '2020-01-01',
    Birthday: '2017-01-01',
    StuNO: 0,
    Address: '',
    ClassTypeName: "萌萌班",
    Email: "1434424321@qq.com",
    Id: 19
}, {
    Role: "SmallStudent",
    Grade: "小班",
    Name: "王博",
    LinkName1: "周倩",
    Age: 6,
    Sex: "男",
    Tel1: 13658018176,
    Relation1: "母子",
    LinkName2: "",
    Relation2: "",
    Tel2: "",
    Arrive: "09:40",
    LeaveSchool: "17:50",
    Attendance: "迟到",
    StateName: "正常",
    OperatorName: "admin",
    CreateTime: '2020-01-01',
    Birthday: '2017-01-01',
    StuNO: 0,
    Address: '',
    ClassTypeName: "火箭班",
    Email: "1434424345@qq.com",
    Id: 20
}];

/* 所有学生 */
var AllStudentList = BigStudentList.concat(MidStudentList).concat(SmallStudentList);

/*老师  */
var TeacherList = [{
        role: "1",
        Name: "王印",
        Age: 20,
        Sex: "女",
        Tel: 13982053096,
        DepName: "教学部",
        Duty: "主任教师",
        Id: "011",
        Grade: "大班",
        arrive: "08:20",
        LeaveSchool: "17:40",
        attendance: "正常",
        StateName: "正常",
        Email: "123456789@qq.com",
        Account: "13982053096",
        PassWord: "123456",
        State: "在职",
        DepID: 1,
        Birthday: "",
        EContact: "金始显",
        ETel: "19823456754",
        Addr: "四川省成都市高新区云华路333号8栋521",
        Url: "images/1.png"
    },
    {
        role: "1",
        Id: "012",
        Name: "小龙",
        Age: 25,
        Sex: "女",
        Tel: 13658018195,
        DepName: "教学部",
        Duty: "主任教师",
        Grade: "中班",
        arrive: "08:20",
        LeaveSchool: "17:30",
        attendance: "正常",
        StateName: "正常",
        Email: "223456789@qq.com",
        Account: "",
        PassWord: "123456",
        State: "在职",
        DepID: 1,
        Birthday: "",
        EContact: "陈财桂",
        ETel: "14456789345",
        Addr: "四川省成都市高新区云华路333号8栋521",
        Url: "images/2.png"
    }, {
        Id: "013",
        role: "2",
        Name: "康康",
        Age: 20,
        Sex: "男",
        Tel: 13658018100,
        DepName: "教学部",
        Duty: "主任教师",
        Grade: "小班",
        arrive: "08:20",
        LeaveSchool: "17:40",
        attendance: "正常",
        StateName: "正常",
        Email: "323456789@qq.com",
        Account: "kangkang",
        PassWord: "123456",
        State: "在职",
        DepID: 1,
        Birthday: "",
        EContact: "苏宇钧",
        ETel: "18823456787",
        Addr: "四川省成都市高新区云华路333号8栋521",
        Url: "images/3.png"
    }, {
        Id: "014",
        role: "1",
        Name: "苏嘉",
        Age: 25,
        Sex: "女",
        Tel: 13880196380,
        DepName: "教学部",
        Duty: "辅助教师",
        Grade: "大班",
        arrive: "08:20",
        LeaveSchool: "17:00",
        attendance: "正常",
        StateName: "正常",
        Email: "423456789@qq.com",
        Account: "",
        PassWord: "123456",
        State: "在职",
        DepID: 1,
        Birthday: "",
        EContact: "陈财桂",
        ETel: "12312312122",
        Addr: "四川省成都市高新区云华路333号8栋521",
        Url: "images/5.png"
    },
    {
        Id: "015",
        role: "1",
        Name: "刘杰",
        Age: 24,
        Sex: "男",
        Tel: 13980016923,
        DepName: "教学部",
        Duty: "辅助教师",
        Grade: "中班",
        arrive: "09:10",
        LeaveSchool: "17:50",
        attendance: "迟到",
        StateName: "正常",
        Email: "523456789@qq.com",
        Account: "",
        PassWord: "123456",
        State: "在职",
        DepID: 1,
        Birthday: "",
        EContact: "杨聪晨",
        ETel: "12312343423",
        Addr: "四川省成都市高新区云华路333号8栋521",
        Url: "images/4.png"
    }, {
        Id: "016",
        role: "1",
        Name: "小丁丁",
        Age: 24,
        Sex: "女",
        Tel: 13880339011,
        DepName: "教学部",
        Duty: "辅助教师",
        Grade: "小班",
        arrive: " ",
        LeaveSchool: " ",
        attendance: "缺勤",
        Email: "623456789@qq.com",
        Account: "",
        PassWord: "123456",
        State: "在职",
        DepID: 1,
        Birthday: "",
        EContact: "张致牛",
        ETel: "1232234556",
        Addr: "四川省成都市高新区云华路333号8栋521",
        Url: "images/pic1.png"
    }
];



/* 后勤部门*/
var BackofficeMaList = [{
    role: "3",
    Name: "毛成君",
    Age: 40,
    Sex: "男",
    Tel: 13981253596,
    DepName: "后勤部",
    Duty: "后勤主管",
    Id: "101",
    Grade: "无",
    arrive: "08:20",
    LeaveSchool: "18:40",
    attendance: "正常",
    StateName: "正常",
    Email: "112312312@qq.com",
    Account: "37532173",
    PassWord: "123456",
    State: "在职",
    DepID: 1,
    Birthday: "",
    EContact: "朱兴聪",
    ETel: "13233245667",
    Addr: "四川省成都市高新区云华路333号8栋521",
    Url: "images/4.png"
}, {
    role: "3",
    Name: "宋玉红",
    Age: 35,
    Sex: "女",
    Tel: 13923245667,
    DepName: "后勤部",
    Duty: "园医主管",
    Id: "102",
    Grade: "无",
    arrive: "08:20",
    LeaveSchool: "17:40",
    attendance: "正常",
    StateName: "正常",
    Email: "12312312322@qq.com",
    Account: "3123344",
    PassWord: "123456",
    State: "在职",
    DepID: 1,
    Birthday: "",
    EContact: "卢育明",
    ETel: "13232345667",
    Addr: "四川省成都市高新区云华路333号8栋521",
    Url: "images/1.png"
}, {
    role: "2",
    Name: "李娜",
    Age: 28,
    Sex: "女",
    Tel: 13923415667,
    DepName: "后勤部",
    Duty: "园医医生",
    Id: "103",
    Grade: "无",
    arrive: "09:20",
    LeaveSchool: "17:40",
    attendance: "迟到",
    StateName: "正常",
    Email: "1231234543@qq.com",
    Account: "",
    PassWord: "123456",
    State: "在职",
    DepID: 1,
    Birthday: "",
    EContact: "梁志纪",
    ETel: "13232342312",
    Addr: "四川省成都市高新区云华路333号8栋521",
    Url: "images/5.png"
}, {
    role: "2",
    Name: "张恒",
    Age: 28,
    Sex: "男",
    Tel: 13923413321,
    DepName: "后勤部",
    Duty: "园医医生",
    Id: "104",
    Grade: "无",
    arrive: "",
    LeaveSchool: "",
    attendance: "缺勤",
    StateName: "正常",
    Email: "1112345566@qq.com",
    Account: "",
    PassWord: "123456",
    State: "离职",
    DepID: 1,
    Birthday: "",
    EContact: "姬坤毅",
    ETel: "12232342312",
    Addr: "四川省成都市高新区云华路333号8栋521",
    Url: "images/3.png"
}, {
    role: "2",
    Name: "王铮",
    Age: 35,
    Sex: "男",
    Tel: 18823221221,
    DepName: "后勤部",
    Duty: "班车司机",
    Id: "105",
    Grade: "无",
    arrive: "08:20",
    LeaveSchool: "18:40",
    attendance: "正常",
    StateName: "正常",
    Email: "无",
    Account: "",
    PassWord: "123456",
    State: "在职",
    DepID: 1,
    Birthday: "",
    EContact: "王戚申",
    ETel: "13232342312",
    Addr: "四川省成都市高新区云华路333号8栋521",
    Url: "images/4.png"
}, {
    role: "3",
    Name: "范子健",
    Age: 32,
    Sex: "男",
    Tel: 13423226677,
    DepName: "后勤部",
    Duty: "食堂主管",
    Id: "106",
    Grade: "无",
    arrive: "08:20",
    LeaveSchool: "18:50",
    attendance: "正常",
    StateName: "正常",
    Email: "332145677@qq.com",
    Account: "",
    PassWord: "123456",
    State: "在职",
    DepID: 1,
    Birthday: "",
    EContact: "陆成苏",
    ETel: "18332342312",
    Addr: "",
    Url: ""
}, {
    role: "2",
    Name: "李兴龙",
    Age: 35,
    Sex: "男",
    Tel: 14423215532,
    DepName: "后勤部",
    Duty: "食堂厨师",
    Id: "107",
    Grade: "无",
    arrive: "08:20",
    LeaveSchool: "18:50",
    attendance: "正常",
    StateName: "正常",
    Email: "1231234352@qq.com",
    Account: "",
    PassWord: "123456",
    State: "在职",
    DepID: 1,
    Birthday: "",
    EContact: "时御梦",
    ETel: "18332343333",
    Addr: "",
    Url: ""
}];

/* role 0 --超级管理员 1 园长，2 老师，  */
/* 行政部门 */
var AdminDeptList = [{
        role: "0",
        Name: "超级管理员",
        Age: 50,
        Sex: "男",
        Tel: 18188886666,
        DepName: "行政部",
        Duty: "超级管理员",
        Id: "99",
        Grade: "无",
        arrive: "08:20",
        LeaveSchool: "18:50",
        attendance: "正常",
        StateName: "正常",
        Email: "11234456678@qq.com",
        Account: "admin",
        PassWord: "123456",
        State: "在职",
        DepID: 1,
        Birthday: "",
        EContact: "",
        ETel: "",
        Addr: "四川省成都市高新区云华路333号8栋521",
        Url: "images/1.png"
    },
    {
        role: "1",
        Name: "周克涛",
        Age: 50,
        Sex: "男",
        Tel: 18188886666,
        DepName: "行政部",
        Duty: "行政园长",
        Id: "001",
        Grade: "无",
        arrive: "08:20",
        LeaveSchool: "18:50",
        attendance: "正常",
        StateName: "正常",
        Email: "11234456678@qq.com",
        Account: "3321323001",
        PassWord: "123456",
        State: "在职",
        DepID: 1,
        Birthday: "1977-1-1",
        EContact: "张三",
        ETel: "13123832833",
        Addr: "四川省成都市高新区云华路333号8栋521",
        Url: "images/4.png"
    }, {
        role: "1",
        Name: "董燕",
        Age: 48,
        Sex: "女",
        Tel: 13788299382,
        DepName: "行政部",
        Duty: "教学园长",
        Id: "002",
        Grade: "无",
        arrive: "08:20",
        LeaveSchool: "18:50",
        attendance: "正常",
        StateName: "正常",
        Email: "12312322334@qq.com",
        Account: "3321323002",
        PassWord: "123456",
        State: "在职",
        DepID: 1,
        Birthday: "1989-1-1",
        EContact: "李四",
        ETel: "15223453732",
        Addr: "四川省成都市高新区云华路333号8栋521",
        Url: "images/2.png"
    }, {
        role: "4",
        Name: "黄婷",
        Age: 35,
        Sex: "女",
        Tel: 13233245556,
        DepName: "行政部",
        Duty: "出纳",
        Id: "003",
        Grade: "无",
        arrive: "08:10",
        LeaveSchool: "18:30",
        attendance: "正常",
        StateName: "正常",
        Email: "123321345543@qq.com",
        Account: "ls",
        PassWord: "123456",
        State: "在职",
        DepID: 1,
        Birthday: "",
        EContact: "",
        ETel: "",
        Addr: "",
        Url: ""
    }, {
        role: "4",
        Name: "苏静怡",
        Age: 27,
        Sex: "女",
        Tel: 13222245126,
        DepName: "行政部",
        Duty: "会计",
        Id: "004",
        Grade: "无",
        arrive: "08:15",
        LeaveSchool: "18:50",
        attendance: "正常",
        StateName: "正常",
        Email: "4546756673221@qq.com",
        Account: "",
        PassWord: "123456",
        State: "在职",
        DepID: 1,
        Birthday: "",
        EContact: "",
        ETel: "",
        Addr: "四川省成都市高新区云华路333号8栋521",
        Url: "images/5.png"
    }
];




/*所有员工*/
var AllStaffList = AdminDeptList.concat(BackofficeMaList).concat(TeacherList);

/* 老师请假 */
var TeacherLeaveList = [{
        role: "2",
        Name: "王芳",
        Age: 28,
        Sex: "女",
        Tel: 13982053096,
        Duty: "主任教师",
        grade: "大班",
        leaveDayForm: "2018/12/1",
        LeaveDayTo: "2018/12/1",
        leaveTimeForm: "09:00",
        leaveTimeTo: "11:00",
        ratify: "已批准",
        Email: "123456789@qq.com"
    },
    {
        role: "2",
        Name: "王芳",
        Age: 28,
        Sex: "女",
        Tel: 13982053096,
        Duty: "主任教师",
        grade: "大班",
        leaveDayForm: "2018/12/10",
        LeaveDayTo: "2018/12/10",
        leaveTimeForm: "14:00",
        leaveTimeTo: "17:30",
        ratify: "已批准",
        Email: "123456789@qq.com"
    },
    {
        role: "2",
        Name: "王芳",
        Age: 28,
        Sex: "女",
        Tel: 13982053096,
        Duty: "主任教师",
        grade: "大班",
        leaveDayForm: "2018/12/17",
        LeaveDayTo: "2018/12/18",
        leaveTimeForm: "09:00",
        leaveTimeTo: "09:00",
        ratify: "未批准",
        Email: "123456789@qq.com"
    },
    {
        role: "2",
        Name: "王芳",
        Age: 28,
        Sex: "女",
        Tel: 13982053096,
        Duty: "主任教师",
        grade: "大班",
        leaveDayForm: "2018/12/24",
        LeaveDayTo: "2018/12/26",
        leaveTimeForm: "09:00",
        leaveTimeTo: "09:00",
        ratify: "待批准",
        Email: "123456789@qq.com"
    }
];
/* 老师请假 */
var TeacherLeaveList = [{
        Role: "2",
        Name: "王芳",
        Age: 28,
        Sex: "女",
        Tel: 13982053096,
        Duty: "主任教师",
        Grade: "大班",
        leaveDayForm: "2018/12/1",
        LeaveDayTo: "2018/12/1",
        leaveTimeForm: "09:00",
        leaveTimeTo: "11:00",
        ratify: "已批准",
        Email: "123456789@qq.com"
    },
    {
        Role: "2",
        Name: "王芳",
        Age: 28,
        Sex: "女",
        Tel: 13982053096,
        Duty: "主任教师",
        Grade: "大班",
        leaveDayForm: "2018/12/10",
        LeaveDayTo: "2018/12/10",
        leaveTimeForm: "14:00",
        leaveTimeTo: "17:30",
        ratify: "已批准",
        Email: "123456789@qq.com"
    },
    {
        Role: "2",
        Name: "王芳",
        Age: 28,
        Sex: "女",
        Tel: 13982053096,
        Duty: "主任教师",
        Grade: "大班",
        leaveDayForm: "2018/12/17",
        LeaveDayTo: "2018/12/18",
        leaveTimeForm: "09:00",
        leaveTimeTo: "09:00",
        ratify: "未批准",
        Email: "123456789@qq.com"
    },
    {
        Role: "2",
        Name: "王芳",
        Age: 28,
        Sex: "女",
        Tel: 13982053096,
        Duty: "主任教师",
        Grade: "大班",
        leaveDayForm: "2018/12/24",
        LeaveDayTo: "2018/12/26",
        leaveTimeForm: "09:00",
        leaveTimeTo: "09:00",
        ratify: "待批准",
        Email: "123456789@qq.com"
    }
];